Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Ferrari 488 Pista
Ferrari 488 Pista
Ferrari 488 Pista
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
The user fournisseur15 has been logged
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
User fournisseur15 successfully logged in
User fournisseur15 successfully logged in
User admin successfully logged in
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Signup failed: Invalid user data
Bad Request: /user/signup
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
User admin successfully logged in
User admin successfully logged in
Signup failed: Invalid user data
Bad Request: /user/signup
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\back\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\back\settings.py changed, reloading.
Watching for file changes with StatReloader
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\back\settings.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\16\EasyLaw\back\back\settings.py changed, reloading.
Watching for file changes with StatReloader
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
User admin successfully logged in
Watching for file changes with StatReloader
Watching for file changes with StatReloader
User admin successfully logged in
Watching for file changes with StatReloader
Signup failed: Invalid user data
Bad Request: /user/signup
Internal Server Error: /user/signup
Traceback (most recent call last):
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py", line 39, in signup
    Client.objects.create(user=user)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\models.py", line 111, in assign_client_group
    instance.user.groups.add(Group.objects.get(name='Client'))
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.
Signup failed: Invalid user data
Bad Request: /user/signup
Signup failed: Invalid user data
Bad Request: /user/signup
Internal Server Error: /user/signup
Traceback (most recent call last):
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py", line 39, in signup
    Client.objects.create(user=user)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\models.py", line 111, in assign_client_group
    instance.user.groups.add(Group.objects.get(name='Client'))
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.
Signup failed: Invalid user data
Bad Request: /user/signup
Internal Server Error: /user/signup
Traceback (most recent call last):
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py", line 39, in signup
    Client.objects.create(user=user)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\base.py", line 924, in save_base
    post_save.send(
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\dispatch\dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\models.py", line 111, in assign_client_group
    instance.user.groups.add(Group.objects.get(name='Client'))
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
django.contrib.auth.models.Group.DoesNotExist: Group matching query does not exist.
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\models.py changed, reloading.
Watching for file changes with StatReloader
Signup failed: Invalid user data
Bad Request: /user/signup
Signup failed: Invalid user data
Bad Request: /user/signup
User fournisseur22 signed up as a client
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Signup failed: Invalid user data
Bad Request: /user/signup
User fournisseur23 signed up as a client
Internal Server Error: /user/signup
Traceback (most recent call last):
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py", line 64, in signup
    confirmation_url = reverse('confirm-email', kwargs={'uidb64': uid, 'token': token})
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'confirm-email' not found. 'confirm-email' is not a valid view function or pattern name.
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\urls.py changed, reloading.
Watching for file changes with StatReloader
Signup failed: Invalid user data
Bad Request: /user/signup
User fournisseur24 signed up as a client
Signup failed: Invalid user data
Bad Request: /user/signup
Not Found: /favicon.ico
Signup failed: Invalid user data
Bad Request: /user/signup
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
User fournisseur25 signed up as a client
User admin successfully logged in
User fournisseur25 successfully logged in
User fournisseur26 signed up as a client
Not Found: /
Not Found: /favicon.ico
Not Found: /
User fournisseur26 successfully logged in
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
User fournisseur26 tried to logIn but need to confirm his email
Unauthorized: /user/login
User fournisseur25 tried to logIn but need to confirm his email
Unauthorized: /user/login
User fournisseur25 tried to logIn but need to confirm his email
Unauthorized: /user/login
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
User fournisseur25 tried to logIn but need to confirm his email
Unauthorized: /user/login
User fournisseur25 tried to logIn but need to confirm his email
Unauthorized: /user/login
User fournisseur25 tried to logIn but need to confirm his email
Unauthorized: /user/login
User fournisseur24 tried to logIn but need to confirm his email
Unauthorized: /user/login
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
User fournisseur24 tried to logIn but need to confirm his email
Unauthorized: /user/login
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
User fournisseur24 successfully logged in
Login failed: Invalid credentials
Unauthorized: /user/login
User fournisseur25 successfully logged in
Login failed: Invalid credentials
Unauthorized: /user/login
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/login
Traceback (most recent call last):
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py", line 151, in login
    if not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Login failed: Invalid credentials
Unauthorized: /user/login
User fournisseur25 successfully logged in
User fournisseur25 successfully logged in
Login failed: Invalid credentials
Unauthorized: /user/login
User fournisseur26 successfully logged in
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
User fournisseur26 successfully logged in
User fournisseur26 successfully logged in
User fournisseur27 signed up as a client
Login failed: Invalid credentials
Unauthorized: /user/login
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/login
Traceback (most recent call last):
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py", line 149, in login
    if not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/login
Traceback (most recent call last):
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py", line 152, in login
    if not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /user/login
Traceback (most recent call last):
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\mps\AppData\Local\Programs\Python\Python310\lib\site-packages\rest_framework\decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py", line 152, in login
    if not user.is_active:
AttributeError: 'NoneType' object has no attribute 'is_active'
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
Login failed: Invalid credentials
Unauthorized: /user/login
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
User fournisseur27 tried to log in but the account is inactive
Forbidden: /user/login
Login failed: Invalid credentials
Unauthorized: /user/login
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\mps\Downloads\2CS\S2\Project\Plateforme\17\EasyLaw\back\User\views.py changed, reloading.
Watching for file changes with StatReloader
User fournisseur27 successfully logged in
